program: sbert_sweep.py
name: stmpnetv1_sweep
project: Machine-Generated-Text-Detection
run_cap: 12
method: bayes
metric:
  name: val_acc
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 3
  eta: 2
parameters:
  learning_rate:
    values: [5e-5, 2e-5, 1e-5, 5e-6, 2e-6, 1e-6]
  batch_size:
    values: [32, 64]
  model_name:
    value: sentence-transformers/all-mpnet-base-v1
  max_len:
    value: 512
  random_seed:
    value: 42
  num_epochs:
    value: 20
  early_stop:
    value: 5
  num_workers:
    value: 8
  device:
    value: cuda
  train_data_path:
    value: ./data/SubtaskB/enrich_comp_data/train_set_comp.jsonl
  dev_data_path:
    value: ./data/SubtaskB/enrich_comp_data/val_set_comp.jsonl
  test_data_path:
    value: ./data/SubtaskB/enrich_comp_data/test_set_comp.jsonls